### ISSUE TITLE
Баги в окне "Словарь"

### ISSUE THREAD

**Issue by theact1on** [luparev22/XEngl#16]
Баги:
- Пустые слова записываются в файл
- При достаточно длинной строке ввода слова/перевода, таблица расширяется
- Кнопки расположены криво
- Поиск по таблице включается на любую из нажатых клавиш, что доставляет дискомфорт
- Вводимый в поля записи текст, может быть написан абсолютно любыми символами, отличными от букв алфавита

**Comment by kchipson** [comment]
Баг:

- 1 символ вводимый в поля записи, может быть написан абсолютно любыми символами, отличными от букв алфавита
