### ISSUE TITLE
Инфобар не исчезает при возврате в главное меню из других окон

### ISSUE THREAD

**Issue by kchipson** [luparev22/XEngl#18]
Баг:
<p class="bug" align="center"><img src="https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1SnCbKmoD4UUKsO8bcFPKbb_jCP7MXf9o" height="100%" width="100%"></p>

Улучшение:
- Плавное появление инфобара поверх основного окна.

**Comment by theact1on** [comment]
Исправлено! && Реализовано!
